# Generated by Django 3.2.13 on 2022-05-22 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20220522_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('price', models.FloatField(verbose_name='Price')),
                ('tags', models.CharField(max_length=255, verbose_name='Tags')),
                ('discount', models.FloatField(verbose_name='Discount')),
                ('description', models.TextField(verbose_name='Description')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seller')),
            ],
        ),
    ]
