# Generated by Django 3.2.13 on 2022-05-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
