# Generated by Django 3.2.13 on 2022-05-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
        ('shop', '0003_auto_20220525_1325'),
    ]

    operations = [
    ]
