# Generated by Django 3.2.13 on 2022-05-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220523_1547'),
        ('accounts', '0008_auto_20220522_1152'),
    ]

    operations = [
    ]
