# Generated by Django 3.2.13 on 2022-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220525_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Admin', 'Admin'), ('Buyer', 'Buyer')], default='Buyer', max_length=10, verbose_name='User Type'),
        ),
    ]
